services:
  web:
    build: .
    ports:
      - "5004:5000"
    restart: unless-stopped
    environment:
      TRINO_URL: http://trino1:8080
      TRINO_USER: log_search
      TRINO_CATALOG: iceberg
      TRINO_SCHEMA: logs
      TRINO_SYSLOG_TABLE: syslog_events
      TRINO_AUTHLOG_TABLE: authlog_events
      TRINO_TIMESTAMP_COLUMN: ts
      TRINO_TIMESTAMP_EXPRESSION:
    extra_hosts:
      - "trino1:192.168.11.18"
